name: 'pytest-reporter'
description: 'Pytest GitHub coverage reporter'
inputs:
  package-manager:
    description: 'Python package manager. Pip is default'
    required: false
    default: 'pip'
  requirements-file:
    description: 'Path to the requirements file if you use pip. ./requirements.txt by default'
    required: false
    default: './requirements.txt'
  pytest-root-dir:
    description: 'root directory to recursively search for .py files'
    required: false
    default: '.'
  pytest-tests-dir:
    description: 'directory with pytest tests. if left empty will identify test(s) dir by default'
    required: false
    default: './'
  cov-omit-list:
    description: 'list of directories and/or files to ignore'
    required: false
    default: ''
  cov-threshold-single:
    description: 'fail if any single file coverage is less than threshold'
    required: false
    default: 0
  cov-threshold-total:
    description: 'fail if the total coverage is less than threshold'
    required: false
    default: 0
outputs:
  output-table: # id of output
    description: 'pytest-cov markdown output table'
  cov-threshold-single-fail:
    description: 'boolean if any single file coverage less than cov-threshold-single'
  cov-threshold-total-fail:
    description: 'boolean if total coverage less than cov-threshold-total'
runs:
  using: "composite"
  steps:
    - id: copy-coverage-processor
      run: cp ${{ github.action_path }}/coverage_processor.py .
      shell: bash
    - id: run-tests
      run: |
        ${{ github.action_path }}/entrypoint.sh \
        "${{ inputs.package-manager }}" \
        "${{ inputs.requirements-file }}" \
        "${{ inputs.pytest-root-dir }}" \
        "${{ inputs.pytest-tests-dir }}" \
        "${{ inputs.cov-omit-list }}" \
        ${{ inputs.cov-threshold-single }} \
        ${{ inputs.cov-threshold-total }} \
      shell: bash
    - id: check-threashold
      run: |
        if [ "${{ steps.run-tests.outputs.cov-threshold-single-fail }}" == "true" ]; then
          echo "cov single fail ${{ steps.run-tests.outputs.cov-threshold-single-fail }}";
          exit 1;
        elif [ "${{ steps.run-tests.outputs.cov-threshold-total-fail }}"  == "true" ]; then
          echo "cov single fail ${{ steps.run-tests.outputs.cov-threshold-total-fail }}";
          exit 1;
        fi
      shell: bash
    - run: |
        echo "Sha: $(git rev-parse --short HEAD)"
        echo "SHORT_SHA=`echo ${{github.event.after}} | cut -c1-7`" >> $GITHUB_ENV
        echo "PULL_NUMBER=`echo ${{ github.event.pull_request.number }}`" >> $GITHUB_ENV
        echo "COMMIT_URL=`echo https://github.com/${{ github.repository }}/pull/${{ github.event.pull_request.number }}/commits/${{ github.event.after }}`" >> $GITHUB_ENV
      shell: bash
    - uses: peter-evans/find-comment@v1
      id: fc
      with:
        issue-number: ${{ github.event.pull_request.number }}
        comment-author: 'github-actions[bot]'
        direction: last
    - uses: peter-evans/create-or-update-comment@v1
      with:
        issue-number: ${{env.PULL_NUMBER}}
        comment-id: ${{ steps.fc.outputs.comment-id }}
        body: |
          ## Tests coverage table for [${{ env.SHORT_SHA }}](${{ env.COMMIT_URL }}) commit.
          ${{ steps.run-tests.outputs.output-table }}
        edit-mode: replace